/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alibaba.dts.formats.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6007968107069830267L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"fields\":[{\"name\":\"Id\",\"type\":\"string\"},{\"name\":\"MessageBodyId\",\"type\":\"string\"},{\"name\":\"MessageTemplateId\",\"type\":\"string\"},{\"name\":\"ProviderCode\",\"type\":\"string\"},{\"name\":\"Subject\",\"type\":\"string\"},{\"name\":\"SendTo\",\"type\":\"string\"},{\"name\":\"SendAt\",\"type\":\"string\"},{\"name\":\"Sent\",\"type\":\"string\"},{\"name\":\"Read\",\"type\":\"string\"},{\"name\":\"ReadAt\",\"type\":\"string\"},{\"name\":\"IsCancel\",\"type\":\"string\"},{\"name\":\"CreatedById\",\"type\":\"string\"},{\"name\":\"CreatedAt\",\"type\":\"string\"},{\"name\":\"UpdatedById\",\"type\":\"string\"},{\"name\":\"UpdatedAt\",\"type\":\"string\"},{\"name\":\"DeletedById\",\"type\":\"string\"},{\"name\":\"Deleted\",\"type\":\"string\"},{\"name\":\"DeletedAt\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Message> ENCODER =
      new BinaryMessageEncoder<Message>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Message> DECODER =
      new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Message> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Message> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Message to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Message from a ByteBuffer. */
  public static Message fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Id;
  @Deprecated public java.lang.CharSequence MessageBodyId;
  @Deprecated public java.lang.CharSequence MessageTemplateId;
  @Deprecated public java.lang.CharSequence ProviderCode;
  @Deprecated public java.lang.CharSequence Subject;
  @Deprecated public java.lang.CharSequence SendTo;
  @Deprecated public java.lang.CharSequence SendAt;
  @Deprecated public java.lang.CharSequence Sent;
  @Deprecated public java.lang.CharSequence Read;
  @Deprecated public java.lang.CharSequence ReadAt;
  @Deprecated public java.lang.CharSequence IsCancel;
  @Deprecated public java.lang.CharSequence CreatedById;
  @Deprecated public java.lang.CharSequence CreatedAt;
  @Deprecated public java.lang.CharSequence UpdatedById;
  @Deprecated public java.lang.CharSequence UpdatedAt;
  @Deprecated public java.lang.CharSequence DeletedById;
  @Deprecated public java.lang.CharSequence Deleted;
  @Deprecated public java.lang.CharSequence DeletedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message() {}

  /**
   * All-args constructor.
   * @param Id The new value for Id
   * @param MessageBodyId The new value for MessageBodyId
   * @param MessageTemplateId The new value for MessageTemplateId
   * @param ProviderCode The new value for ProviderCode
   * @param Subject The new value for Subject
   * @param SendTo The new value for SendTo
   * @param SendAt The new value for SendAt
   * @param Sent The new value for Sent
   * @param Read The new value for Read
   * @param ReadAt The new value for ReadAt
   * @param IsCancel The new value for IsCancel
   * @param CreatedById The new value for CreatedById
   * @param CreatedAt The new value for CreatedAt
   * @param UpdatedById The new value for UpdatedById
   * @param UpdatedAt The new value for UpdatedAt
   * @param DeletedById The new value for DeletedById
   * @param Deleted The new value for Deleted
   * @param DeletedAt The new value for DeletedAt
   */
  public Message(java.lang.CharSequence Id, java.lang.CharSequence MessageBodyId, java.lang.CharSequence MessageTemplateId, java.lang.CharSequence ProviderCode, java.lang.CharSequence Subject, java.lang.CharSequence SendTo, java.lang.CharSequence SendAt, java.lang.CharSequence Sent, java.lang.CharSequence Read, java.lang.CharSequence ReadAt, java.lang.CharSequence IsCancel, java.lang.CharSequence CreatedById, java.lang.CharSequence CreatedAt, java.lang.CharSequence UpdatedById, java.lang.CharSequence UpdatedAt, java.lang.CharSequence DeletedById, java.lang.CharSequence Deleted, java.lang.CharSequence DeletedAt) {
    this.Id = Id;
    this.MessageBodyId = MessageBodyId;
    this.MessageTemplateId = MessageTemplateId;
    this.ProviderCode = ProviderCode;
    this.Subject = Subject;
    this.SendTo = SendTo;
    this.SendAt = SendAt;
    this.Sent = Sent;
    this.Read = Read;
    this.ReadAt = ReadAt;
    this.IsCancel = IsCancel;
    this.CreatedById = CreatedById;
    this.CreatedAt = CreatedAt;
    this.UpdatedById = UpdatedById;
    this.UpdatedAt = UpdatedAt;
    this.DeletedById = DeletedById;
    this.Deleted = Deleted;
    this.DeletedAt = DeletedAt;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Id;
    case 1: return MessageBodyId;
    case 2: return MessageTemplateId;
    case 3: return ProviderCode;
    case 4: return Subject;
    case 5: return SendTo;
    case 6: return SendAt;
    case 7: return Sent;
    case 8: return Read;
    case 9: return ReadAt;
    case 10: return IsCancel;
    case 11: return CreatedById;
    case 12: return CreatedAt;
    case 13: return UpdatedById;
    case 14: return UpdatedAt;
    case 15: return DeletedById;
    case 16: return Deleted;
    case 17: return DeletedAt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Id = (java.lang.CharSequence)value$; break;
    case 1: MessageBodyId = (java.lang.CharSequence)value$; break;
    case 2: MessageTemplateId = (java.lang.CharSequence)value$; break;
    case 3: ProviderCode = (java.lang.CharSequence)value$; break;
    case 4: Subject = (java.lang.CharSequence)value$; break;
    case 5: SendTo = (java.lang.CharSequence)value$; break;
    case 6: SendAt = (java.lang.CharSequence)value$; break;
    case 7: Sent = (java.lang.CharSequence)value$; break;
    case 8: Read = (java.lang.CharSequence)value$; break;
    case 9: ReadAt = (java.lang.CharSequence)value$; break;
    case 10: IsCancel = (java.lang.CharSequence)value$; break;
    case 11: CreatedById = (java.lang.CharSequence)value$; break;
    case 12: CreatedAt = (java.lang.CharSequence)value$; break;
    case 13: UpdatedById = (java.lang.CharSequence)value$; break;
    case 14: UpdatedAt = (java.lang.CharSequence)value$; break;
    case 15: DeletedById = (java.lang.CharSequence)value$; break;
    case 16: Deleted = (java.lang.CharSequence)value$; break;
    case 17: DeletedAt = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Id' field.
   * @return The value of the 'Id' field.
   */
  public java.lang.CharSequence getId() {
    return Id;
  }

  /**
   * Sets the value of the 'Id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.Id = value;
  }

  /**
   * Gets the value of the 'MessageBodyId' field.
   * @return The value of the 'MessageBodyId' field.
   */
  public java.lang.CharSequence getMessageBodyId() {
    return MessageBodyId;
  }

  /**
   * Sets the value of the 'MessageBodyId' field.
   * @param value the value to set.
   */
  public void setMessageBodyId(java.lang.CharSequence value) {
    this.MessageBodyId = value;
  }

  /**
   * Gets the value of the 'MessageTemplateId' field.
   * @return The value of the 'MessageTemplateId' field.
   */
  public java.lang.CharSequence getMessageTemplateId() {
    return MessageTemplateId;
  }

  /**
   * Sets the value of the 'MessageTemplateId' field.
   * @param value the value to set.
   */
  public void setMessageTemplateId(java.lang.CharSequence value) {
    this.MessageTemplateId = value;
  }

  /**
   * Gets the value of the 'ProviderCode' field.
   * @return The value of the 'ProviderCode' field.
   */
  public java.lang.CharSequence getProviderCode() {
    return ProviderCode;
  }

  /**
   * Sets the value of the 'ProviderCode' field.
   * @param value the value to set.
   */
  public void setProviderCode(java.lang.CharSequence value) {
    this.ProviderCode = value;
  }

  /**
   * Gets the value of the 'Subject' field.
   * @return The value of the 'Subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return Subject;
  }

  /**
   * Sets the value of the 'Subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.Subject = value;
  }

  /**
   * Gets the value of the 'SendTo' field.
   * @return The value of the 'SendTo' field.
   */
  public java.lang.CharSequence getSendTo() {
    return SendTo;
  }

  /**
   * Sets the value of the 'SendTo' field.
   * @param value the value to set.
   */
  public void setSendTo(java.lang.CharSequence value) {
    this.SendTo = value;
  }

  /**
   * Gets the value of the 'SendAt' field.
   * @return The value of the 'SendAt' field.
   */
  public java.lang.CharSequence getSendAt() {
    return SendAt;
  }

  /**
   * Sets the value of the 'SendAt' field.
   * @param value the value to set.
   */
  public void setSendAt(java.lang.CharSequence value) {
    this.SendAt = value;
  }

  /**
   * Gets the value of the 'Sent' field.
   * @return The value of the 'Sent' field.
   */
  public java.lang.CharSequence getSent() {
    return Sent;
  }

  /**
   * Sets the value of the 'Sent' field.
   * @param value the value to set.
   */
  public void setSent(java.lang.CharSequence value) {
    this.Sent = value;
  }

  /**
   * Gets the value of the 'Read' field.
   * @return The value of the 'Read' field.
   */
  public java.lang.CharSequence getRead() {
    return Read;
  }

  /**
   * Sets the value of the 'Read' field.
   * @param value the value to set.
   */
  public void setRead(java.lang.CharSequence value) {
    this.Read = value;
  }

  /**
   * Gets the value of the 'ReadAt' field.
   * @return The value of the 'ReadAt' field.
   */
  public java.lang.CharSequence getReadAt() {
    return ReadAt;
  }

  /**
   * Sets the value of the 'ReadAt' field.
   * @param value the value to set.
   */
  public void setReadAt(java.lang.CharSequence value) {
    this.ReadAt = value;
  }

  /**
   * Gets the value of the 'IsCancel' field.
   * @return The value of the 'IsCancel' field.
   */
  public java.lang.CharSequence getIsCancel() {
    return IsCancel;
  }

  /**
   * Sets the value of the 'IsCancel' field.
   * @param value the value to set.
   */
  public void setIsCancel(java.lang.CharSequence value) {
    this.IsCancel = value;
  }

  /**
   * Gets the value of the 'CreatedById' field.
   * @return The value of the 'CreatedById' field.
   */
  public java.lang.CharSequence getCreatedById() {
    return CreatedById;
  }

  /**
   * Sets the value of the 'CreatedById' field.
   * @param value the value to set.
   */
  public void setCreatedById(java.lang.CharSequence value) {
    this.CreatedById = value;
  }

  /**
   * Gets the value of the 'CreatedAt' field.
   * @return The value of the 'CreatedAt' field.
   */
  public java.lang.CharSequence getCreatedAt() {
    return CreatedAt;
  }

  /**
   * Sets the value of the 'CreatedAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.CreatedAt = value;
  }

  /**
   * Gets the value of the 'UpdatedById' field.
   * @return The value of the 'UpdatedById' field.
   */
  public java.lang.CharSequence getUpdatedById() {
    return UpdatedById;
  }

  /**
   * Sets the value of the 'UpdatedById' field.
   * @param value the value to set.
   */
  public void setUpdatedById(java.lang.CharSequence value) {
    this.UpdatedById = value;
  }

  /**
   * Gets the value of the 'UpdatedAt' field.
   * @return The value of the 'UpdatedAt' field.
   */
  public java.lang.CharSequence getUpdatedAt() {
    return UpdatedAt;
  }

  /**
   * Sets the value of the 'UpdatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.CharSequence value) {
    this.UpdatedAt = value;
  }

  /**
   * Gets the value of the 'DeletedById' field.
   * @return The value of the 'DeletedById' field.
   */
  public java.lang.CharSequence getDeletedById() {
    return DeletedById;
  }

  /**
   * Sets the value of the 'DeletedById' field.
   * @param value the value to set.
   */
  public void setDeletedById(java.lang.CharSequence value) {
    this.DeletedById = value;
  }

  /**
   * Gets the value of the 'Deleted' field.
   * @return The value of the 'Deleted' field.
   */
  public java.lang.CharSequence getDeleted() {
    return Deleted;
  }

  /**
   * Sets the value of the 'Deleted' field.
   * @param value the value to set.
   */
  public void setDeleted(java.lang.CharSequence value) {
    this.Deleted = value;
  }

  /**
   * Gets the value of the 'DeletedAt' field.
   * @return The value of the 'DeletedAt' field.
   */
  public java.lang.CharSequence getDeletedAt() {
    return DeletedAt;
  }

  /**
   * Sets the value of the 'DeletedAt' field.
   * @param value the value to set.
   */
  public void setDeletedAt(java.lang.CharSequence value) {
    this.DeletedAt = value;
  }

  /**
   * Creates a new Message RecordBuilder.
   * @return A new Message RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Message.Builder newBuilder() {
    return new com.alibaba.dts.formats.avro.Message.Builder();
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Message.Builder newBuilder(com.alibaba.dts.formats.avro.Message.Builder other) {
    return new com.alibaba.dts.formats.avro.Message.Builder(other);
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Message instance.
   * @param other The existing instance to copy.
   * @return A new Message RecordBuilder
   */
  public static com.alibaba.dts.formats.avro.Message.Builder newBuilder(com.alibaba.dts.formats.avro.Message other) {
    return new com.alibaba.dts.formats.avro.Message.Builder(other);
  }

  /**
   * RecordBuilder for Message instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.lang.CharSequence Id;
    private java.lang.CharSequence MessageBodyId;
    private java.lang.CharSequence MessageTemplateId;
    private java.lang.CharSequence ProviderCode;
    private java.lang.CharSequence Subject;
    private java.lang.CharSequence SendTo;
    private java.lang.CharSequence SendAt;
    private java.lang.CharSequence Sent;
    private java.lang.CharSequence Read;
    private java.lang.CharSequence ReadAt;
    private java.lang.CharSequence IsCancel;
    private java.lang.CharSequence CreatedById;
    private java.lang.CharSequence CreatedAt;
    private java.lang.CharSequence UpdatedById;
    private java.lang.CharSequence UpdatedAt;
    private java.lang.CharSequence DeletedById;
    private java.lang.CharSequence Deleted;
    private java.lang.CharSequence DeletedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MessageBodyId)) {
        this.MessageBodyId = data().deepCopy(fields()[1].schema(), other.MessageBodyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MessageTemplateId)) {
        this.MessageTemplateId = data().deepCopy(fields()[2].schema(), other.MessageTemplateId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ProviderCode)) {
        this.ProviderCode = data().deepCopy(fields()[3].schema(), other.ProviderCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Subject)) {
        this.Subject = data().deepCopy(fields()[4].schema(), other.Subject);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SendTo)) {
        this.SendTo = data().deepCopy(fields()[5].schema(), other.SendTo);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SendAt)) {
        this.SendAt = data().deepCopy(fields()[6].schema(), other.SendAt);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Sent)) {
        this.Sent = data().deepCopy(fields()[7].schema(), other.Sent);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Read)) {
        this.Read = data().deepCopy(fields()[8].schema(), other.Read);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ReadAt)) {
        this.ReadAt = data().deepCopy(fields()[9].schema(), other.ReadAt);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.IsCancel)) {
        this.IsCancel = data().deepCopy(fields()[10].schema(), other.IsCancel);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CreatedById)) {
        this.CreatedById = data().deepCopy(fields()[11].schema(), other.CreatedById);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CreatedAt)) {
        this.CreatedAt = data().deepCopy(fields()[12].schema(), other.CreatedAt);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.UpdatedById)) {
        this.UpdatedById = data().deepCopy(fields()[13].schema(), other.UpdatedById);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.UpdatedAt)) {
        this.UpdatedAt = data().deepCopy(fields()[14].schema(), other.UpdatedAt);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.DeletedById)) {
        this.DeletedById = data().deepCopy(fields()[15].schema(), other.DeletedById);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Deleted)) {
        this.Deleted = data().deepCopy(fields()[16].schema(), other.Deleted);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.DeletedAt)) {
        this.DeletedAt = data().deepCopy(fields()[17].schema(), other.DeletedAt);
        fieldSetFlags()[17] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Message instance
     * @param other The existing instance to copy.
     */
    private Builder(com.alibaba.dts.formats.avro.Message other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MessageBodyId)) {
        this.MessageBodyId = data().deepCopy(fields()[1].schema(), other.MessageBodyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MessageTemplateId)) {
        this.MessageTemplateId = data().deepCopy(fields()[2].schema(), other.MessageTemplateId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ProviderCode)) {
        this.ProviderCode = data().deepCopy(fields()[3].schema(), other.ProviderCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Subject)) {
        this.Subject = data().deepCopy(fields()[4].schema(), other.Subject);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SendTo)) {
        this.SendTo = data().deepCopy(fields()[5].schema(), other.SendTo);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SendAt)) {
        this.SendAt = data().deepCopy(fields()[6].schema(), other.SendAt);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.Sent)) {
        this.Sent = data().deepCopy(fields()[7].schema(), other.Sent);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.Read)) {
        this.Read = data().deepCopy(fields()[8].schema(), other.Read);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ReadAt)) {
        this.ReadAt = data().deepCopy(fields()[9].schema(), other.ReadAt);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.IsCancel)) {
        this.IsCancel = data().deepCopy(fields()[10].schema(), other.IsCancel);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CreatedById)) {
        this.CreatedById = data().deepCopy(fields()[11].schema(), other.CreatedById);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CreatedAt)) {
        this.CreatedAt = data().deepCopy(fields()[12].schema(), other.CreatedAt);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.UpdatedById)) {
        this.UpdatedById = data().deepCopy(fields()[13].schema(), other.UpdatedById);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.UpdatedAt)) {
        this.UpdatedAt = data().deepCopy(fields()[14].schema(), other.UpdatedAt);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.DeletedById)) {
        this.DeletedById = data().deepCopy(fields()[15].schema(), other.DeletedById);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Deleted)) {
        this.Deleted = data().deepCopy(fields()[16].schema(), other.Deleted);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.DeletedAt)) {
        this.DeletedAt = data().deepCopy(fields()[17].schema(), other.DeletedAt);
        fieldSetFlags()[17] = true;
      }
    }

    /**
      * Gets the value of the 'Id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return Id;
    }

    /**
      * Sets the value of the 'Id' field.
      * @param value The value of 'Id'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Id' field has been set.
      * @return True if the 'Id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Id' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearId() {
      Id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'MessageBodyId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageBodyId() {
      return MessageBodyId;
    }

    /**
      * Sets the value of the 'MessageBodyId' field.
      * @param value The value of 'MessageBodyId'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setMessageBodyId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MessageBodyId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageBodyId' field has been set.
      * @return True if the 'MessageBodyId' field has been set, false otherwise.
      */
    public boolean hasMessageBodyId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'MessageBodyId' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearMessageBodyId() {
      MessageBodyId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'MessageTemplateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageTemplateId() {
      return MessageTemplateId;
    }

    /**
      * Sets the value of the 'MessageTemplateId' field.
      * @param value The value of 'MessageTemplateId'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setMessageTemplateId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.MessageTemplateId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'MessageTemplateId' field has been set.
      * @return True if the 'MessageTemplateId' field has been set, false otherwise.
      */
    public boolean hasMessageTemplateId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'MessageTemplateId' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearMessageTemplateId() {
      MessageTemplateId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ProviderCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getProviderCode() {
      return ProviderCode;
    }

    /**
      * Sets the value of the 'ProviderCode' field.
      * @param value The value of 'ProviderCode'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setProviderCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ProviderCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ProviderCode' field has been set.
      * @return True if the 'ProviderCode' field has been set, false otherwise.
      */
    public boolean hasProviderCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ProviderCode' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearProviderCode() {
      ProviderCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'Subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return Subject;
    }

    /**
      * Sets the value of the 'Subject' field.
      * @param value The value of 'Subject'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.Subject = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'Subject' field has been set.
      * @return True if the 'Subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'Subject' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearSubject() {
      Subject = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'SendTo' field.
      * @return The value.
      */
    public java.lang.CharSequence getSendTo() {
      return SendTo;
    }

    /**
      * Sets the value of the 'SendTo' field.
      * @param value The value of 'SendTo'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setSendTo(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.SendTo = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'SendTo' field has been set.
      * @return True if the 'SendTo' field has been set, false otherwise.
      */
    public boolean hasSendTo() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'SendTo' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearSendTo() {
      SendTo = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'SendAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getSendAt() {
      return SendAt;
    }

    /**
      * Sets the value of the 'SendAt' field.
      * @param value The value of 'SendAt'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setSendAt(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.SendAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'SendAt' field has been set.
      * @return True if the 'SendAt' field has been set, false otherwise.
      */
    public boolean hasSendAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'SendAt' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearSendAt() {
      SendAt = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'Sent' field.
      * @return The value.
      */
    public java.lang.CharSequence getSent() {
      return Sent;
    }

    /**
      * Sets the value of the 'Sent' field.
      * @param value The value of 'Sent'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setSent(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.Sent = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'Sent' field has been set.
      * @return True if the 'Sent' field has been set, false otherwise.
      */
    public boolean hasSent() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'Sent' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearSent() {
      Sent = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'Read' field.
      * @return The value.
      */
    public java.lang.CharSequence getRead() {
      return Read;
    }

    /**
      * Sets the value of the 'Read' field.
      * @param value The value of 'Read'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setRead(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.Read = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'Read' field has been set.
      * @return True if the 'Read' field has been set, false otherwise.
      */
    public boolean hasRead() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'Read' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearRead() {
      Read = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'ReadAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getReadAt() {
      return ReadAt;
    }

    /**
      * Sets the value of the 'ReadAt' field.
      * @param value The value of 'ReadAt'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setReadAt(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.ReadAt = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'ReadAt' field has been set.
      * @return True if the 'ReadAt' field has been set, false otherwise.
      */
    public boolean hasReadAt() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'ReadAt' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearReadAt() {
      ReadAt = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'IsCancel' field.
      * @return The value.
      */
    public java.lang.CharSequence getIsCancel() {
      return IsCancel;
    }

    /**
      * Sets the value of the 'IsCancel' field.
      * @param value The value of 'IsCancel'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setIsCancel(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.IsCancel = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'IsCancel' field has been set.
      * @return True if the 'IsCancel' field has been set, false otherwise.
      */
    public boolean hasIsCancel() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'IsCancel' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearIsCancel() {
      IsCancel = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'CreatedById' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedById() {
      return CreatedById;
    }

    /**
      * Sets the value of the 'CreatedById' field.
      * @param value The value of 'CreatedById'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setCreatedById(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.CreatedById = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'CreatedById' field has been set.
      * @return True if the 'CreatedById' field has been set, false otherwise.
      */
    public boolean hasCreatedById() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'CreatedById' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearCreatedById() {
      CreatedById = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'CreatedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return CreatedAt;
    }

    /**
      * Sets the value of the 'CreatedAt' field.
      * @param value The value of 'CreatedAt'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.CreatedAt = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'CreatedAt' field has been set.
      * @return True if the 'CreatedAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'CreatedAt' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearCreatedAt() {
      CreatedAt = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpdatedById' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedById() {
      return UpdatedById;
    }

    /**
      * Sets the value of the 'UpdatedById' field.
      * @param value The value of 'UpdatedById'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setUpdatedById(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.UpdatedById = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'UpdatedById' field has been set.
      * @return True if the 'UpdatedById' field has been set, false otherwise.
      */
    public boolean hasUpdatedById() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'UpdatedById' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearUpdatedById() {
      UpdatedById = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'UpdatedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedAt() {
      return UpdatedAt;
    }

    /**
      * Sets the value of the 'UpdatedAt' field.
      * @param value The value of 'UpdatedAt'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setUpdatedAt(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.UpdatedAt = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'UpdatedAt' field has been set.
      * @return True if the 'UpdatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'UpdatedAt' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearUpdatedAt() {
      UpdatedAt = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeletedById' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeletedById() {
      return DeletedById;
    }

    /**
      * Sets the value of the 'DeletedById' field.
      * @param value The value of 'DeletedById'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setDeletedById(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.DeletedById = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'DeletedById' field has been set.
      * @return True if the 'DeletedById' field has been set, false otherwise.
      */
    public boolean hasDeletedById() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'DeletedById' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearDeletedById() {
      DeletedById = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'Deleted' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeleted() {
      return Deleted;
    }

    /**
      * Sets the value of the 'Deleted' field.
      * @param value The value of 'Deleted'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setDeleted(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.Deleted = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'Deleted' field has been set.
      * @return True if the 'Deleted' field has been set, false otherwise.
      */
    public boolean hasDeleted() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'Deleted' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearDeleted() {
      Deleted = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeletedAt' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeletedAt() {
      return DeletedAt;
    }

    /**
      * Sets the value of the 'DeletedAt' field.
      * @param value The value of 'DeletedAt'.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder setDeletedAt(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.DeletedAt = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'DeletedAt' field has been set.
      * @return True if the 'DeletedAt' field has been set, false otherwise.
      */
    public boolean hasDeletedAt() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'DeletedAt' field.
      * @return This builder.
      */
    public com.alibaba.dts.formats.avro.Message.Builder clearDeletedAt() {
      DeletedAt = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Message build() {
      try {
        Message record = new Message();
        record.Id = fieldSetFlags()[0] ? this.Id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.MessageBodyId = fieldSetFlags()[1] ? this.MessageBodyId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.MessageTemplateId = fieldSetFlags()[2] ? this.MessageTemplateId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ProviderCode = fieldSetFlags()[3] ? this.ProviderCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.Subject = fieldSetFlags()[4] ? this.Subject : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.SendTo = fieldSetFlags()[5] ? this.SendTo : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.SendAt = fieldSetFlags()[6] ? this.SendAt : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.Sent = fieldSetFlags()[7] ? this.Sent : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.Read = fieldSetFlags()[8] ? this.Read : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.ReadAt = fieldSetFlags()[9] ? this.ReadAt : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.IsCancel = fieldSetFlags()[10] ? this.IsCancel : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.CreatedById = fieldSetFlags()[11] ? this.CreatedById : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.CreatedAt = fieldSetFlags()[12] ? this.CreatedAt : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.UpdatedById = fieldSetFlags()[13] ? this.UpdatedById : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.UpdatedAt = fieldSetFlags()[14] ? this.UpdatedAt : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.DeletedById = fieldSetFlags()[15] ? this.DeletedById : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.Deleted = fieldSetFlags()[16] ? this.Deleted : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.DeletedAt = fieldSetFlags()[17] ? this.DeletedAt : (java.lang.CharSequence) defaultValue(fields()[17]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Message>
    WRITER$ = (org.apache.avro.io.DatumWriter<Message>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Message>
    READER$ = (org.apache.avro.io.DatumReader<Message>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
